### ISSUE TITLE
Swarm crashes, then fails to restart (1.1.2; multiple networks; might be related to "error locating sandbox")

### ISSUE THREAD

**Issue by jpetazzo** [docker/classicswarm#1913]
What I did (approximately):
- I have a Compose application spanning multiple networks
- I scaled a service (on network A) to 100 instances
- I scaled a service (on network B) to 100 instances
- I have a load balancer between the two networks
- at first, I saw bursts of errors like the following:
  
  ```
  System error: nosandbox: error locating sandbox id 23d5e3ec0012ee0b180fa2bb320b0c0d130cc601
  84fbf048135b728bec63f33e: no sandbox found
  ```
- so I remove everything with `docker-compose down` and retried
- then Swarm stopped responsing
- `docker ps` on the node showed that it was restarting and crashing instantly, in a loop
- I have other nodes in a redundant setup and they all crash in a loop, too
- swarm version 1.1.2 (f947993)

Logs are attached.

I'll wipe the cluster so I can continue to work, but let me know what I can do if this happens again to gather more data.

[swarm.log.txt](https://github.com/docker/swarm/files/153560/swarm.log.txt)

**Comment by chanwit** [comment]
@jpetazzo A network-related problem also bugged me and I accidentally found a workaround. The good news is that you don't need to wipe the whole the cluster.

The workaround is to clean up the cluster store (in my case `consul`) by recursive delete all keys there. After that, wait until all nodes registering themselves again, all overlay networks will be gone and you'll be good to go.

This bug seems to be for docker/libnetwork anyway.
