### ISSUE TITLE
two containers with same name on different node cause swarm issues

### ISSUE THREAD

**Issue by allencloud** [docker/classicswarm#2064]
Hi, All

How to reproduce issue easily:
1. run a container with name `allen` on each docker engine(192.168.2.56,192.168.2.59):

```
docker run -d --name allen ubuntu:14.04 sleep 1000
```

2.start swarm managers:

```
$GOPATH/bin/swarm -l debug manage -H tcp://0.0.0.0:2375 nodes://192.168.2.59:2376,192.168.2.56:2376
```

3.docker ps (swarm ps ):

```
root@ubuntu:~/wordpress# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
3527c441d94b        ubuntu:14.04        "sleep 1000"        10 seconds ago      Up 9 seconds                            ubuntu/allen
6e25e521e50b        ubuntu:14.04        "sleep 1000"        17 seconds ago      Up 17 seconds                           ubuntu/allen
```
1. docker stop allen & docker inspect allen  (swarm stop & swarm inspect)

```
root@ubuntu:~/wordpress# docker stop allen
Failed to stop container (allen): Error response from daemon: No such container: allen
No such container: allen
root@ubuntu:~/wordpress# docker inspect allen
[]
Error: No such image or container: allen
```

some strange things happened in this case.
Maybe swarm can remind user of more than one container with this name exist in the cluster, instead of reporting `no such container`.

And I think volumes and networks have the same issue.

**Comment by doronp** [comment]
Wouldn't be nice to be able to have 2 containers with the same name even on the same engine, let alone on the same Swarm cluster - What are there IDs for ;-)

**Comment by allencloud** [comment]
2 containers with the same name even on the same engine?
Can it happen on the same engine?

**Comment by doronp** [comment]
As it stands this is not possible not in Swarm (unless you do your own scenario in which you 'went around' Swarm ) and definitely not in the engine.

Reason being - There is specific check for that as you know. Also when querying a container one can use name as a unique identifier.

But Why I ask - If we have unique ID - Why should a unique name  be forced? It is certainly possible to allow duplicate names both in Swarm and Engine However big is the change. 

Makes sense?

**Comment by dongluochen** [comment]
I think the reason Docker Engine does not allow name duplicate is usability. First it's hard for human to remember container ID. We prefer container names. Second orchestration tools can create names and use that in automation. For example Docker Compose creates web_1, web_2, ..., worker_1, worker_2, etc. IMHO allowing duplicate name would add unnecessary complexity and confusion.

**Comment by ezrasilvera** [comment]
@dongluochen I think there are two different issues here:
1) The general issue of using unique resource names in Docker engine (container names, volume names, etx..). And using this names as the "display names"
2) The original problem that @allencloud posted which is related but belongs to a different class of issues: Should Swarm be able to connect to existing Docker engines and be able to discover and manage the resources on this new "cluster"  Even if such resources  couldn't be created originally with Swarm.
If we do want to support (2) - we need to decide how do we manage such conflicts. Do we just send a warning ? Do we disable the offending resources? etc..
I specifically say "resources" and not "containers"  Because as I said I can see the same problem with other cluster wide resources such as overlay NWs and distributed volumes.

**Comment by allencloud** [comment]
@ezrasilvera @dongluochen 
That is true.
From my point of view. it is good to support (2), but some kind of conflict, we had better handle it peacefully, at least do not report some message which is not the truth.
