### ISSUE TITLE
Swarm cluster using Docker for Mac

### ISSUE THREAD

**Issue by arun-gupta** [docker/classicswarm#2327]
Creating a Docker Swarm cluster with Docker Machine is super easy. Here is a sample script:

https://gist.github.com/arun-gupta/c42cacfa3225727f5c71ff4a5dc547dc

Docker for Mac is limited to a single host on Mac. Would like support for either multiple hosts so that a Swarm cluster can be created. Alternatively, add an option to Docker for Mac such that a Swarm cluster is created with all the underlying plumbing automatically taken care of.

**Comment by everett-toews** [comment]
There's interest in this feature in the forums too at [Feature Request: Multiple VMs (Docker for Mac)](https://forums.docker.com/t/feature-request-multiple-vms/9264).

**Comment by jamroks** [comment]
+1 for multiple vm, "xhyve" i guess, on to which a swarm cluster could be created

**Comment by thaJeztah** [comment]
As a "playground" setup for Docker Swarm, have a look at https://github.com/tianon/docker-dind-cluster, which uses docker-in-docker to create a Swarm cluster. Obviously not for any serious work, but a quick way to play/learn working with swarm

**Comment by xiaods** [comment]
@thaJeztah 's way is prefered.

**Comment by xiaods** [comment]
@thaJeztah do you have some playbook on tianon/docker-dind-cluster image

**Comment by thaJeztah** [comment]
@xiaods no, don't have, but he used it in a presentation, https://github.com/tianon/2016-container-summit-vegas

**Comment by alexei-led** [comment]
It's possible to run Docker Swarm cluster in Docker for Mac, using docker-in-docker images. 
Take a look at this [post](https://medium.com/@alexeiled/docker-swarm-cluster-with-docker-in-docker-on-macos-bdbb97d6bb07#.862v5fkji), it contains code snippets to achieve this task

**Comment by thaJeztah** [comment]
@alexei-led nifty! thanks for that link! I was actually still planning to update some parts of the docs to use docker-in-docker (as a playground for getting familiar with the swarm features); so far I used "all" docker-in-docker for that, but using the xhyve VM IP may be a nice one to use as it allows published services to be reached as "normal".

I noticed you're pinning docker to `1.12.1`; may want to remove the `.1`, so that the latest 1.12.x version is used. I also had to make a minor change to the loop (add a `&&` before the join, and `;` after);

```
for i in $(seq "${NUM_WORKERS}"); do \
    docker run -d --privileged --name worker-${i} \
    --hostname=worker-${i} -p ${i}2375:2375 docker:1.12.1-dind \
    && docker --host=localhost:${i}2375 \
    swarm join --token ${SWARM_TOKEN} ${SWARM_MASTER}:2377; \
done
```

/cc @manomarks; you may be interested in that as well for your demo setups

**Comment by thaJeztah** [comment]
oh, also; I'd recommend adding a `-v` / `--volume` for `/var/lib/docker`, so that the graph-store is not stored in the container's CoW filesystem. Using a volume for it prevents the performance penalty for that, and also allows you to use (e.g.) the `overlay2` storage driver on the workers, instead of `vfs` (which is very slow);

So either; `-v /var/lib/docker` for an "anonymous" volume, or (e.g.) `--volume=worker-${i}:/var/lib/docker` to have a "persistent" volume (which would allow upgrading a worker without loosing it's images/containers)

**Comment by xiaods** [comment]
Cool. it good way.
