### ISSUE TITLE
Why have all issues been closed?

### ISSUE THREAD

**Issue by schmunk42** [docker/classicswarm#2985]
Surely not all were for `swarmkit` and even if you are going to deprecate `classicswarm` it makes no sense to just close all issues, so what's the rationale behind this action?

**Comment by justincormack** [comment]
The vast majority of issues were from 5 years ago when it was being actively developed, and the recent ones were all mistakes for swarmkit, other than some issues I resolved. Many were issues in components or Moby or other software and may be resolved. It is GitHubs (reasonable) recommendation that you close issues and PRs before archiving a repository so that people know they are not being worked on, and I was also looking to see if anyone came forward to say that they were still working on things or, indeed, actively using Swarm Classic.

**Comment by justincormack** [comment]
As per #2986 this project is going to be archived.
